### ISSUE TITLE
Not working in Android 10

### ISSUE THREAD

**Issue by fmonclus** [piruin/phototaker#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
        at me.piruin.phototaker.PhotoTaker$CropAction.action(PhotoTaker.java:278)
        at me.piruin.phototaker.PhotoTaker.doCropImage(PhotoTaker.java:131)
        at me.piruin.phototaker.PhotoTaker$1.OnScanned(PhotoTaker.java:57)
        at me.piruin.phototaker.ContentUriScanner$1.run(ContentUriScanner.java:51)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by vomobile** [comment]
Any one resolved?
